"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
"""

def test_sum_of_even_valued_fibonacci_numbers():
    pass

def get_fibonacci_sequence(max_sequence: int):
    pass

def sum_of_even_valued_fibonacci_numbers() -> int:
    """Sum of even valued Fibonacci numbers.

    The values of the Fibonacci sequence should not exceed four millions.

    Returns:
        int: returned sum.
    """
    pass
